language: objective-c
osx_image: xcode8

cache:
  - bundler
  - cocoapods

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - xcodebuild -workspace 'RxExpect.xcworkspace' -scheme 'RxExpect' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
