language: objective-c
osx_image: xcode8.3
sudo: false

env:
  global:
    - PROJECT="RxExpect.xcodeproj"
    - IOS_SDK="iphonesimulator10.3" 
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.3"
    - MACOS_SDK="macosx10.12"
    - MACOS_DESTINATION="arch=x86_64"
  matrix:
    - SCHEME="RxExpect-iOS"       SDK="$IOS_SDK"      DESTINATION="$IOS_DESTINATION"
    - SCHEME="RxExpect-macOS"     SDK="$MACOS_SDK"    DESTINATION="$MACOS_DESTINATION"

install:
  - carthage checkout --no-use-binaries
  - carthage build

script:
  - set -o pipefail && xcodebuild clean test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Release
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
